### ISSUE TITLE
how to use  SHTOOLS to transfom a file of spherical harmonic coefficients into grid form?

### ISSUE THREAD

**Issue by Lydia823** [SHTOOLS/SHTOOLS#95] opened 2017-07-27 01:54 UTC
Now i have a data file 'abc', the data of which are spherical harmonic coefficients, like this:
2 0 -20.7431 0
2 1 -3.01236 6.55421
2 2 34.5977 23.6613
3 0 5.01478 0
...
20 18 1.34793e-07 3.67997e-07
20 19 -8.29264e-07 -2.27977e-07
20 20 -3.88784e-08 -6.72354e-07

Could i use pyshtools to transform these data into grid data? like this:
lon lat value
...

i try to do it like this:
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> import pyshtools as pst

>>>a=np.loadtxt('abc')
>>>np.save('abc',a)
>>>clm=pst.SHCoeffs.from_file('abc.npy',lmax=20)

but got some errors:
 Error --- SHRead
 Problem reading first line of cmb_sph.npy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cc/.pyenv/versions/anaconda3-4.1.0/lib/python3.5/site-packages/pyshtools/shclasses/shcoeffsgrid.py", line 393, in from_file
    coeffs, lmax = _shtools.SHRead(fname, lmax, **kwargs)
  File "/home/cc/.pyenv/versions/anaconda3-4.1.0/lib/python3.5/site-packages/pyshtools/shtools/__init__.py", line 200, in wrapped_func
    raise SHToolsError(_shtools_status_message(returned_values[0]))
pyshtools.shtools.SHToolsError: File IO error.
>>> 

so how should i use pyshtools to do it?

**Comment by MarkWieczorek** [comment] 2017-07-27 08:27
Here is the documentation
~~~~
Usage
-----
x = SHCoeffs.from_file(filename, lmax, [format='shtools', kind,
                                        normalization, csphase, skip])
x = SHCoeffs.from_file(filename, [format='npy', kind, normalization,
                                  csphase, **kwargs])
~~~~
You could probably use either 

`clm=pst.SHCoeffs.from_file('abc',lmax=20)`
or 
`clm=pst.SHCoeffs.from_file('abc.npy', format='npy')`

**Comment by Lydia823** [comment] 2017-07-27 12:04
@MarkWieczorek  i used the method as you listed, but still got errors:

>>> import matplotlib as plt
>>> import numpy as np
>>> import pyshtools as pst
>>> clm=pst.SHCoeffs.from_file('abc.npy',format='npy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cc/.pyenv/versions/anaconda3-4.1.0/lib/python3.5/site-packages/pyshtools/shclasses/shcoeffsgrid.py", line 407, in from_file
    csphase=csphase)
  File "/home/cc/.pyenv/versions/anaconda3-4.1.0/lib/python3.5/site-packages/pyshtools/shclasses/shcoeffsgrid.py", line 1275, in __init__
    self.coeffs[~mask] = 0.
IndexError: too many indices for array


I don't know why.

**Comment by MarkWieczorek** [comment] 2017-07-27 12:39
Please just use 

`clm=pst.SHCoeffs.from_file('texfile',lmax=20)`

where `textfile` is the ascii file containing your coefficients as listed above. I have verified that this works. 

If you decide to read in a numpy file, you will first need to save the coefficients in the correct format. The numpy file should be for a matrix that contains only the coefficients, and not the degree and orders in the way that you have saved it.

**Comment by Lydia823** [comment] 2017-07-27 12:56
@MarkWieczorek  thanks a lot, now i can read the coefficients into shtools just as textfile. i don't want to read in a numpy file.
I also want to ask you whether the degree of the coefficients should be start from 0. My coefficient file was started from degree 2.

**Comment by Lydia823** [comment] 2017-07-27 13:19
My aim is to use shtools to transform spherical harmonic coefficients into grid form and then save the grid data . If i want to save the grid file transformed from coefficient file into ascii file like this:
lon lat value
...
how to achive that using to_file() methods?

**Comment by MarkWieczorek** [comment] 2017-07-27 14:06
That format is not supported by the class interface. However, you can easily code this yourself by expanding the grid using 

`grid = clm.expand()`

and then using the `grid.lats()` and `grid.lons()` methods. 

As this is not a bug, I am closing this issue.

**Closed by MarkWieczorek** 2017-07-27 14:06 UTC
