### ISSUE TITLE
jupyter is an (undeclared) build-time dependency

### ISSUE THREAD

**Issue by QuLogic** [SHTOOLS/SHTOOLS#440] opened 2024-01-30 03:12 UTC
The chain unconditionally goes `meson.build` -> `examples/meson.build` -> `examples/notebooks/meson.build`, and in the last file is a call to `find_program('jupyter')`. But this defaults to `required:true`, meaning that that program is required to build. However, it is not listed in the `build-system.requires` entry in `pyproject.toml`. It also isn't in the runtime dependencies or, e.g., a "test" optional dependency list.

If you're building a normal (non-editable) install, then build isolation is enabled, but it won't affect `$PATH`, so this probably snuck by. But if you're building in a completely clean environment (cibuildwheel, distro packages, etc.) that just install what's in the metadata, it will fail.

**Comment by vianamp** [comment] 2024-03-14 15:51
I confirm this problem.

**Comment by MarkWieczorek** [comment] 2024-03-14 16:32
This is fixed in the develop branch, and I'll be merging this to master next week.

**Comment by vianamp** [comment] 2024-03-14 17:02
Thank you. Also, not related but, can you please tell me if you ever tried to install pyshtools using Python 3.11?

**Comment by MarkWieczorek** [comment] 2024-03-15 13:35
Are you having a problem with 3.11? It should work.

**Comment by vianamp** [comment] 2024-03-15 16:33
Yes, I can only get pyshtools installed in 3.11 if I pin the version to 4.10.4. I am running ubuntu 18.04.

**Comment by MarkWieczorek** [comment] 2024-03-16 12:31
Could you please open a separate issue, and provide all the necessary details to reproduce and debug this problem? Please also be aware that there are several issues open regarding 4.11 because there is no wheel or conda package available at this time. At this point, installing via pip will install from source, and you will need to install the necessary dependencies.

**Closed by MarkWieczorek** 2024-03-16 12:31 UTC
