### ISSUE TITLE
pyshtools installation error

### ISSUE THREAD

**Issue by fadhli-atarita** [SHTOOLS/SHTOOLS#333] opened 2022-03-01 22:18 UTC
Hello,

I encountered an error while installing pyshtools using pip. All the dependencies + pyfftw are already installed. 

I'm using win10 with python 3.10. Anyone know how to fix this? Thank you.

The error:

Collecting pyshtools
  Using cached pyshtools-4.9.1.tar.gz (37.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      See http://johnmacfarlane.net/pandoc/installing.html
      for installation options
      ---------------------------------------------------------------

      C:\Users\ramaa\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:505: UserWarning: Normalizing 'v4.9.1' to '4.9.1'
        warnings.warn(tmpl.format(**locals()))
      *** pypandoc is not installed. PYPI long_description will not be formatted correctly. ***
      INSTALLING SHTOOLS v4.9.1
      INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      WARN: Could not locate executable f77
      INFO: customize IntelVisualFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifl
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      INFO: customize CompaqVisualFCompiler
      WARN: Could not locate executable DF
      INFO: customize IntelItaniumVisualFCompiler
      WARN: Could not locate executable efl
      INFO: customize Gnu95FCompiler
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      INFO: customize G95FCompiler
      WARN: Could not locate executable g95
      INFO: customize IntelEM64VisualFCompiler
      INFO: customize IntelEM64TFCompiler
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      INFO: customize PGroupFlangCompiler
      WARN: Could not locate executable flang
      searching SHTOOLS in: build\temp.win-amd64-3.10
      INFO: fftw_info:
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO:   libraries fftw3 not found in ['C:\\Users\\ramaa\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\ramaa\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      INFO:   fftw3 not found
      INFO:   libraries rfftw,fftw not found in ['C:\\Users\\ramaa\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\ramaa\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      INFO:   fftw2 not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ramaa\AppData\Local\Temp\pip-install-0bgzarw3\pyshtools_9b27342d23e54910b4522bfe7b4c3a39\setup.py", line 243, in <module>
          setup(**metadata)
        File "C:\Users\ramaa\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "C:\Users\ramaa\AppData\Local\Temp\pip-install-0bgzarw3\pyshtools_9b27342d23e54910b4522bfe7b4c3a39\setup.py", line 194, in configuration
          fftw_info = get_info('fftw', notfound_action=2)
        File "C:\Users\ramaa\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\distutils\system_info.py", line 585, in get_info
          return cl().get_info(notfound_action)
        File "C:\Users\ramaa\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\distutils\system_info.py", line 851, in get_info
          raise self.notfounderror(self.notfounderror.__doc__)
      numpy.distutils.system_info.FFTWNotFoundError:
          FFTW (http://www.fftw.org/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [fftw]) or by setting
          the FFTW environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MarkWieczorek** [comment] 2022-05-02 09:18
Could you try this with the 4.10 release and see if you get the same error? The problem is obviously that FFTW isn't being found.

Also, you might want to look at how we build the wheels for windows. Unfortunately, we are having a problem with the latest release, but it might give you some ideas: https://github.com/SHTOOLS/SHTOOLS/issues/352

**Comment by alxkalinin** [comment] 2022-05-03 10:36
I hope we are near to the provide the binary wheel soon. But if you need to build wheel yourself, please use the following instruction

# Build instructions for Windows

## Development environment

We suppose that the
- [Python 3.10](https://www.python.org/) is installed in the `C:\Dev\Python-3.10`
- [7-zip](https://www.7-zip.org/) is installed in the `C:\Program Files\7-Zip`

## Python 3.10 packages

Upgrade pip and install python development dependencies

```cmd
>>> C:\Dev\Python-3.10\python -m pip install --upgrade pip
>>> C:\Dev\Python-3.10\python -m pip install --upgrade setuptools wheel numpy cython versioneer
```


## MinGW-w64 development environment

### Introduction

SHTOOLS library contains C and Fortran source codes. It means that we need both C and Fortran compilers and GCC (GNU Compiler Collection) provides all what we need.

For the Windows the best way to use GCC is to install MinGW-w64 development environment. Several options are avialable, but the the top are
- [MSYS2](https://www.msys2.org/), a collection of linux-like tools and libraries for building and installing software under the Windows
- [WinLIbs](https://winlibs.com/), standalone MinGW-w64

[MSYS2](https://www.msys2.org/) is the most popular way to install MinGW-w64

### Install MSYS2

To install MSYS2

1. Download latest installation files from the https://www.msys2.org/, at the time of the document writing the file is `msys2-x86_64-20220503.exe`.
2. Install MSYS2 into the `C:\Dev\msys64` folder
3. After the installation run the MSYS2 console
4. In the MSYS2 console upgrade all packages
   
   ```
   $ pacman -Syu
   ```

5. In the MSYS2 console install [MinGW-w64 toolchain](https://packages.msys2.org/group/mingw-w64-x86_64-toolchain)

   ```
   $ pacman -Sy mingw-w64-x86_64-toolchain
   ```

## Build SHTOOLS

### Clone the SHTOOLS repository

```cmd
>>> git clone https://github.com/SHTOOLS/SHTOOLS.git
```

```cmd
>>> dir

 Directory of C:\Projects\sw-dev-python\shtools

2022-05-03  10:40    <DIR>          .
2022-05-03  10:40    <DIR>          ..
2022-05-03  09:35               374 BUILD-WINDOWS.md
2022-05-03  10:42    <DIR>          SHTOOLS
```

### Install development dependencies

SHTOOLS requires FFTW and LAPACK libraries

Download and extract FFTW

```cmd
>>> mkdir fftw
>>> cd fftw
>>> C:\Dev\msys64\usr\bin\wget ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll64.zip
>>> "C:\Program Files\7-Zip\7z" x fftw-3.3.5-dll64.zip
>>> copy libfftw3-3.dll libfftw3.dll
>>> cd .. 
```

Download and extract LAPACK

```cmd
>>> mkdir lapack
>>> cd lapack
>>> set LAPACK_URL=http://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64
>>> C:\Dev\msys64\usr\bin\wget %LAPACK_URL%/libblas.lib
>>> C:\Dev\msys64\usr\bin\wget %LAPACK_URL%/libblas.dll
>>> C:\Dev\msys64\usr\bin\wget %LAPACK_URL%/liblapack.lib
>>> C:\Dev\msys64\usr\bin\wget %LAPACK_URL%/liblapack.dll
>>> cd .. 
```

```cmd
>>> dir

 Directory of C:\Projects\sw-dev-python\shtools

2022-05-03  11:05    <DIR>          .
2022-05-03  11:05    <DIR>          ..
2022-05-03  11:03             2,833 BUILD-WINDOWS.md
2022-05-03  10:53    <DIR>          fftw
2022-05-03  11:05    <DIR>          lapack
2022-05-03  10:42    <DIR>          SHTOOLS
```

### Build SHTOOLS

```cmd
>>> set FFTW=C:\Projects\sw-dev-python\shtools\fftw
>>> set BLAS=C:\Projects\sw-dev-python\shtools\lapack
>>> set LAPACK=C:\Projects\sw-dev-python\shtools\lapack

>>> echo [build]>> C:\Dev\Python-3.10\Lib\site-packages\setuptools\_distutils\distutils.cfg
>>> echo compiler = mingw32>> C:\Dev\Python-3.10\Lib\site-packages\setuptools\_distutils\distutils.cfg

>>> set PYTHON_BUILD_DIR=C:\Projects\sw-dev-python\shtools\SHTOOLS\build\lib.win-amd64-cpython-310
>>> mkdir %PYTHON_BUILD_DIR%\pyshtools
>>> copy %LAPACK%\libblas.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy %LAPACK%\liblapack.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy %FFTW%\libfftw3-3.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy C:\Dev\msys64\mingw64\bin\libgcc_s_seh-1.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy C:\Dev\msys64\mingw64\bin\libgfortran-5.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy C:\Dev\msys64\mingw64\bin\libquadmath-0.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy C:\Dev\msys64\mingw64\bin\libwinpthread-1.dll %PYTHON_BUILD_DIR%\pyshtools
>>> copy C:\Dev\msys64\mingw64\bin\libgfortran-5.dll %PYTHON_BUILD_DIR%\pyshtools\libgfortran_64-3.dll
>>> copy C:\Dev\msys64\mingw64\bin\libgcc_s_seh-1.dll %PYTHON_BUILD_DIR%\pyshtools\libgcc_s_seh_64-1.dll


>>> cd SHTOOLS
>>> C:\Dev\Python-3.10\python -m pip wheel -v -v -v --no-deps --wheel-dir=dist .
```

**Comment by MarkWieczorek** [comment] 2022-05-03 11:46
For info, the windows wheels are now up and working on pypi for v4.10.

**Comment by muyoucun** [comment] 2022-10-17 06:36
have you solved？

**Comment by MarkWieczorek** [comment] 2022-10-17 08:57
Did you try installing using pip since my message on May 3? Please try installing with pip and report any errors you get.

If you use conda, try installing by conda and report any errors that might get.

**Comment by MarkWieczorek** [comment] 2023-05-02 11:42
I am going to close this issue as I believe everything is working now. If this is not the case, please re-open this issue.

**Closed by MarkWieczorek** 2023-05-02 11:42 UTC
