### ISSUE TITLE
Is pyshtools.expand.spharm_lm wrongly vectorized?

### ISSUE THREAD

**Issue by SergeiDBykov** [SHTOOLS/SHTOOLS#277] opened 2021-01-12 17:06 UTC
Hi!

I am trying to use SHTOOLS in my research, more precisely, the module with spherical harmonics (scipy's ones are not correct for high orders). 

I encountered a problem that the function pyshtools.expand.spharm_lm is poorly vectorized.

For example, consider this code:

```
theta = np.array( [np.pi/3, np.pi/6] )
phi = np.array( [np.pi/4, np.pi/10] )
l,m=4,2
```
now I want to see the value of Ylm in those two points:
`print( [ pysh.expand.spharm_lm(l,m,theta[i],phi[i], kind = 'complex', degrees = False) for i in [0,1]] ) `
output: 
`[(4.0844600309605675e-17+0.667042943941768j), (1.019337146628372+0.7405917874011487j)]`
   i.e. this prints correctly Ylm at every point in (theta,phi)
 but when I do
`print(pysh.expand.spharm_lm(l,m,theta,phi, kind = 'complex', degrees = False) `
the output is: 
`[4.08446003e-17+0.66704294j 5.39649078e-01+0.39207801j]`
i.e. not that one would expect with the vectorized input.

I found that  vectorization function from numpy
`Ylm_shtools=np.vectorize(pysh.expand.spharm_lm)' looks like a correct solution:

`print( Ylm_shtools(l,m,theta,phi,kind = 'complex', degrees = False) )`
yields
`[4.08446003e-17+0.66704294j 1.01933715e+00+0.74059179j]`

as expected.

It's not a problem, but rather a possible enhancement, since the scipy.special.sph_harm are not a perfect solution (see [this github issue)](https://github.com/scipy/scipy/issues/7778), whereas your Ylm work fine until l~2700.

Thanks,

Sergei.

**Comment by MarkWieczorek** [comment] 2021-01-13 09:44
Thanks for pointing this out, and letting me know about `np.vectorize` that I wasn't aware of! Do you know if there is some kind of vectorize decorator that could be easily used to do this? A similar problem exists with `legendre_lm()`. At a minimum, we could check if `theta` and `phi` are vectors in the routines, and then just loop over the values and explicitly return an array.

**Comment by QuLogic** [comment] 2021-01-13 23:27
`np.vectorize` works as a decorator.

**Comment by SergeiDBykov** [comment] 2021-01-14 17:20
> Thanks for pointing this out, and letting me know about `np.vectorize` that I wasn't aware of! Do you know if there is some kind of vectorize decorator that could be easily used to do this? A similar problem exists with `legendre_lm()`. At a minimum, we could check if `theta` and `phi` are vectors in the routines, and then just loop over the values and explicitly return an array.

I thing that QuLogic is right. So far I have been using np.vectorize in a way I described and it works very well. Probably you should do as QuLogic proposed.

**Comment by MarkWieczorek** [comment] 2021-01-17 15:30
I'm working on vectorizing these now using np.vectorize, but I noticed something that is a little annoying:

When you get help on the function using `expand.spharm_lm?` in ipython, this returns not only the docstring of the function `spharm_lm`, but also the class docstring of `vectorize`. 

Is this the intended behavior? Or is there a way to not print the class docstring? (I note that `help(spharm_lm)` only prints the function docstring, but I think that the `?` approach is more common.)

**Comment by MarkWieczorek** [comment] 2021-01-23 09:12
The fix is merged into develop. A new release should come out next week, so let me know if you see any problems.

**Closed by MarkWieczorek** 2021-01-23 09:12 UTC

**Comment by SergeiDBykov** [comment] 2021-01-23 22:33
Good to hear, I think I will try it when the new version is out, I’m sure you did much  better than I suggested in the first message! @MarkWieczorek

**Comment by SergeiDBykov** [comment] 2021-02-04 10:30
Ok apparently the update of the package with `conda update` killed my anaconda any python spyder.

**Comment by MarkWieczorek** [comment] 2021-02-04 10:46
Could you give us some debugging information? For example, does pyshtools work in python and ipython for you? And what system are you running this on? Did you try creating a new environment and reinstalling everything? (There are some problems with the jedi package that have been causing problems: try installing the last stable version 0.17.2).

**Comment by SergeiDBykov** [comment] 2021-02-04 12:28
It worked in ipython but all anaconda was broken (I could not even update or install packages). This is for MacOS. In any case I deleted anaconda and reinstalling it, but thanks for advice.

**Comment by MarkWieczorek** [comment] 2021-02-04 22:25
If the problem really is pyshtools, I would suggest that you try installing only the dependencies: It is quite possible that one of the other packages is causing the problem.
